### ISSUE TITLE
When I click play there is only sound but no picture.

### ISSUE THREAD

**Issue by crrow** [opensourcecheemsburgers/RustyTube#13] opened 2024-02-02 04:02 UTC
Sometime even no sound.

------------ 
OS: Manjaro Linux x86_64 
Host: MS-7D42 1.0 
Kernel: 6.6.10-1-MANJARO 
Uptime: 38 mins 
Packages: 1675 (pacman), 32 (brew), 127 (nix-user) 
Shell: zsh 5.9 
Resolution: 3840x2160 
DE: Plasma 5.27.10 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], Fluent [GTK2/3] 
Terminal: HyperTerm 
Terminal Font: JetBrainsMono Nerd Font 
CPU: 12th Gen Intel i5-12600KF (16) @ 4.900GHz 
GPU: NVIDIA GeForce RTX 4070 Ti 
Memory: 23421MiB / 64166MiB

**Comment by opensourcecheemsburgers** [comment] 2024-02-02 10:17
Looks like a duplicate of #3. 

Either change the formats using the format cog in the bottom right of the video, as mentioned in the [README](https://github.com/opensourcecheemsburgers/RustyTube/blob/master/README.md), or use Firefox/Chromium for the time being until a fix is found.

**Closed** 2024-02-10 23:07 UTC
Labels: duplicate
